import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import sharp from 'sharp';
import {
  WAYFINDER_CATEGORIES,
  STATUS_COLOR_KEYS,
  pinImageId,
  createPinSvg,
} from '../src/constants/symbology.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const outputDir = path.join(repoRoot, 'assets', 'pins');

fs.mkdirSync(outputDir, {recursive: true});

const manifestEntries = [];

for (const category of WAYFINDER_CATEGORIES) {
  for (const statusKey of STATUS_COLOR_KEYS) {
    const id = pinImageId(category.key, statusKey);
    const svg = createPinSvg(category.key, statusKey);
    const outputPath = path.join(outputDir, `${id}.png`);
    await sharp(Buffer.from(svg)).png().toFile(outputPath);
    manifestEntries.push({id, file: `${id}.png`});
  }
}

const manifestBody = manifestEntries
  .map(entry => `  '${entry.id}': require('../../assets/pins/${entry.file}'),`)
  .join('\n');

const manifestSource = `/**
 * Auto-generated by scripts/generate_pin_images.mjs
 * Do not edit manually — regenerate after symbology.js changes.
 */
export const PIN_IMAGE_MANIFEST = {
${manifestBody}
};
`;

fs.writeFileSync(path.join(repoRoot, 'src', 'constants', 'pinImages.js'), manifestSource, 'utf8');
console.log(`Generated ${manifestEntries.length} pin images in ${outputDir}`);